# TODO: reference these in the docs:
#       https://github.com/orgs/community/discussions/7730
#       https://github.com/rossjrw/pr-preview-action
#       https://github.com/marketplace/actions/sticky-pull-request-comment
#       https://github.com/JamesIves/github-pages-deploy-action
#       https://github.com/blueedgetechno/win11React/blob/master/.github/workflows/pr-preview.yml

name: Build pull request preview
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
# We need no permissions on this repo
permissions: {}
env:
  VERSION: ${{ github.event.number }}
  PAGES_STORAGE_REPO: mgeier/version-injector-nursery-pull-request-previews
jobs:
  build:
    uses: ./.github/workflows/build-docs.yml

  inject-pr-preview:
    runs-on: ubuntu-latest
    needs: build
    steps:
      # We have no access to secrets here, so we can only get read permissions.
      # Basically, we only need the config file at this point.
      - name: Check out storage repository
        uses: actions/checkout@v4
        with:
          repository: ${{ env.PAGES_STORAGE_REPO }}
      - name: Remove target directory
        run: |
          rm -rf pages/$VERSION
      - uses: actions/download-artifact@v4
        with:
          name: docs
          path: pages/${{ env.VERSION }}
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3
      - name: Install version_injector
        # TODO: "normal" users should install the release from PyPI:
        run: |
          python -m pip install git+https://github.com/mgeier/version-injector-nursery.git@${{ github.ref }}
      - name: Inject PR warnings
        # TODO: implement this!
        run: |
          #python -m version_injector.generic_warning $VERSION
      - uses: actions/upload-artifact@v4
        with:
          name: pr-preview
          path: pages/${{ env.VERSION }}
          include-hidden-files: false
      - uses: actions/upload-artifact@v4
        with:
          name: pr-event
          path: ${{ github.event_path }}
