name: "PR preview: build"
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
# We need no permissions on this repo
permissions: {}
env:
  DOCS: docs
  PR_NUMBER: ${{ github.event.number }}
  PAGES_STORAGE_REPO: mgeier/version-injector-nursery-pull-request-previews
jobs:
  build:
    uses: ./.github/workflows/build-docs.yml

  inject-warning:
    runs-on: ubuntu-latest
    needs: build
    steps:
      # We have no access to secrets here, so we can only get read permissions.
      # Basically, we only need the config file and the templates at this point.
      - name: Check out storage repository
        uses: actions/checkout@v4
        with:
          repository: ${{ env.PAGES_STORAGE_REPO }}
      - name: Remove target directory
        run: |
          rm -rf $DOCS/$PR_NUMBER
      - name: Download built docs
        uses: actions/download-artifact@v4
        with:
          name: docs
          path: ${{ env.DOCS }}/${{ env.PR_NUMBER }}
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3
      - name: Install version_injector
        # TODO: "normal" users should install the release from PyPI:
        run: |
          python -m pip install git+https://github.com/mgeier/version-injector-nursery.git@${{ github.ref }}
      - name: Inject PR warnings
        # TODO: implement this!
        run: |
          #python -m version_injector.generic_warning $PR_NUMBER
      - name: Upload injected docs
        uses: actions/upload-artifact@v4
        with:
          name: pr-preview
          path: ${{ env.DOCS }}/${{ env.PR_NUMBER }}
          include-hidden-files: false
