name: Build pull request preview
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

env:
  VERSION: ${{ github.event.number }}
jobs:
  build:
    uses: ./.github/workflows/build-docs.yml

  deploy-preview:
    runs-on: ubuntu-latest
    steps:
      # TODO: checkout storage/pages repo

      - name: Remove target directory
        run: |
          rm -rf pages/$VERSION
      - uses: actions/download-artifact@v4
        with:
          name: docs
          path: pages/${{ env.VERSION }}
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3
      - name: Install version_injector
        # TODO: "normal" users should install the release from PyPI:
        run: |
          python -m pip install git+https://github.com/mgeier/version-injector-nursery.git
      - name: Inject PR warnings
        # TODO: implement this!
        run: |
          #python -m version_injector.generic_warning $VERSION
      # TODO: commmit
      # TODO: push
      # TODO: create/update PR comment
