name: "PR preview: build"
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
# We need no permissions on this repo
permissions: {}
jobs:
  build:
    uses: ./.github/workflows/build-docs.yml
